name: fsm_example
description: Example
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fsm:
    path: ..
  dfunc: '>=0.3.1 <0.4.0'

dev_dependencies:
  build_runner: ^1.7.4
  pedantic: ^1.8.0
  test: ^1.6.0
  dfunc_builder: '>=0.0.3 <0.1.0'
