name: fsm_example
description: Example
#version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mno_fsm:
    path: ..

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  test: ^1.18.2
