name: fsm_example
description: Example
#version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mno_fsm:
    path: ..
  dfunc: ^0.8.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  test: ^1.21.2
#  dfunc_builder: '>=0.0.3 <0.1.0'
