name: fsm_example
description: Example
#version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mno_fsm:
    path: ..
  dfunc: ^0.7.2

dev_dependencies:
  build_runner: ^2.0.5
  pedantic: ^1.11.1
  test: ^1.17.9
#  dfunc_builder: '>=0.0.3 <0.1.0'
