name: fsm
description: A library for finite state machine realization in Dart. Inspired by Tinder StateMachine for Kotlin.
version: 0.0.5
homepage: https://github.com/ookami-kb/fsm

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dfunc: ^0.7.2

dev_dependencies:
  build_runner: ^2.0.5
  pedantic: ^1.11.1
  test: ^1.17.9
  mockito: ^5.0.10
